version: "2"

services:

  mirror:
    image: registry:2
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/server.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/server.key
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    volumes:
      - ./volume/mirror:/var/lib/registry
      - ./volume/secrets:/secrets:ro
