version: "2"
services:
  raneto:
    image: linuxserver/raneto
#    container_name: raneto
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - ./appdata:/config
    ports:
      - 3000:3000
#    restart: unless-stopped
