version: "2.1"
services:
  raneto:
    image: linuxserver/raneto
    environment:
      - PUID=$PUID
      - PGID=$PFID
      - TZ=Asia/Tokyo
    volumes:
      - ./vol:/config
    ports:
      - $PORT:3000
