version: '3'

services:

  ldap-server:
    image: osixia/openldap:latest
    restart: always
    environment:
      LDAP_ORGANISATION: "org"
      LDAP_DOMAIN: "domain"
    ports:
      - "389:389"
    volumes:
      - lib-ldap:/var/lib/ldap
      - ldap-slapd:/etc/ldap/slapd.d

  ldap-admin:
    image: sra00346/phpldapadmin:latest
#    image: osixia/phpldapadmin:latest
    restart: always
    build:
      context: build/phpldapadmin
      dockerfile: Dockerfile
    environment:
      PHPLDAPADMIN_LDAP_HOST: "ldap-server"
#      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
#      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "80:80"
#    volumes:
#      - phpldapadmin:/var/www/phpldapadmin

  usermin:
    image: sra00346/usermin:latest
    restart: always
    build:
      context: build/usermin
      dockerfile: Dockerfile
    ports:
      - "20000:20000"

volumes:

  lib-ldap:
    driver: local

  ldap-slapd:
    driver: local

#  phpldapadmin:
#    driver: local
