version: '3'

services:
  ldap-server:
    image: osixia/openldap:latest
    restart: always
    environment:
      LDAP_ORGANISATION: "dmaf"

  ldap-admin:
    image: osixia/phpldapadmin:latest
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "80:80"
    volumes:
#      - ./config.php:/container/service/phpldapadmin/assets/config/config.php
      - ./config.php:/container/service/phpldapadmin/assets/config/config.php.my
