version: '3'

services:
  ldap-server:
    image: osixia/openldap:latest
    restart: always
    environment:
      LDAP_ORGANISATION: "org"
      LDAP_DOMAIN: "domain"

  ldap-admin:
    image: osixia/phpldapadmin:latest
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "80:80"
    volumes:
      - ./phpldapadmin:/var/www/phpldapadmin
