version: '3.5'
services:
  dockerhub:
    image: registry:2
    restart: always
    ports:
      - 443:443
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/dockerhub.crt
      REGISTRY_HTTP_TLS_KEY: /certs/dockerhub.key
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - ./volume/certs:/certs
      - ./volume/registry:/var/lib/registry
  frontend:
    image: sra00346/docker-registry-frontend:v2
    build:
      context: build/frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    environment:
      ENV_DOCKER_REGISTRY_HOST: dockerhub
      ENV_DOCKER_REGISTRY_PORT: 443
      ENV_DOCKER_REGISTRY_USE_SSL: 1
    depends_on:
      - dockerhub
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gitbucket
      MYSQL_USER: gitbucket
      MYSQL_PASSWORD: gitbucket
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  gitbucket:
    image: f99aq8ove/gitbucket
    restart: always
    volumes:
      - gitbucket:/gitbucket
    environment:
      GITBUCKET_DB_URL: jdbc:mysql://mysql/gitbucket?useUnicode=true&characterEncoding=utf8mb4&useSSL=false
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: gitbucket
      GITBUCKET_OPTS: --prefix=/gitbucket
      GITBUCKET_EXTRA_DEPS: 'false'
      JAVA_OPTS: -Xmx1g
    expose:
      - 8080
      - 29418
    depends_on:
      - mysql
  jenkins:
    image: jenkins/jenkins:lts-alpine
    restart: always
    volumes:
      - jenkinsdata:/var/jenkins_home
      - ./volume/plugins:/var/jenkins_home/plugins
    environment:
      JENKINS_OPTS: --prefix=/jenkins
      JAVA_OPTS: -Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
    expose:
      - 8080
      - 50000
  mail:
    image: jeanberu/mailcatcher
    expose:
      - 1025
    ports:
      - 1080:1080
volumes:
  gitbucket:
    driver: local
  mysql-data:
    driver: local
  jenkinsdata:
    driver: local

